/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laesmeraldasanfelipe;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Angel Feregrino
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login2
     */
    int xMouse, yMouse;

    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
       // jTextFieldusuario.setEnabled(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/laesmeraldasanfelipe/img/icono.png")));
    
       // SwingUtilities.updateComponentTreeUI(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        NombreLogo = new javax.swing.JLabel();
        bglogo = new javax.swing.JLabel();
        bgcity = new javax.swing.JLabel();
        labeliniciarsesion = new javax.swing.JLabel();
        jLabellogo = new javax.swing.JLabel();
        jLabelusuario = new javax.swing.JLabel();
        jPanelBarra = new javax.swing.JPanel();
        jPanelExt = new javax.swing.JPanel();
        jLabelX = new javax.swing.JLabel();
        jTextFieldusuario = new javax.swing.JTextField();
        jSeparatorusuario = new javax.swing.JSeparator();
        jSeparatorconraseña = new javax.swing.JSeparator();
        jLabelcontraseña = new javax.swing.JLabel();
        jcontraseña = new javax.swing.JPasswordField();
        jPanellogin = new javax.swing.JPanel();
        jLabellogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreLogo.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        NombreLogo.setForeground(new java.awt.Color(255, 255, 255));
        NombreLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreLogo.setText("LA ESMERALDA");
        bg.add(NombreLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 290, 30));

        bglogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bglogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laesmeraldasanfelipe/img/imagelogin-removebg-preview.png"))); // NOI18N
        bg.add(bglogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 290, 170));

        bgcity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laesmeraldasanfelipe/img/city.png"))); // NOI18N
        bgcity.setText("jLabel1");
        bg.add(bgcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 290, 500));

        labeliniciarsesion.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        labeliniciarsesion.setText("INICIAR SESIÓN");
        bg.add(labeliniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabellogo.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabellogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laesmeraldasanfelipe/img/logo.png"))); // NOI18N
        jLabellogo.setText("LA ESMERALDA");
        bg.add(jLabellogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 320, -1));

        jLabelusuario.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabelusuario.setText("Usuario");
        bg.add(jLabelusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jPanelBarra.setBackground(new java.awt.Color(255, 153, 102));
        jPanelBarra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelBarraMouseDragged(evt);
            }
        });
        jPanelBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelBarraMousePressed(evt);
            }
        });

        jPanelExt.setBackground(new java.awt.Color(255, 153, 102));
        jPanelExt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelExtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelExtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelExtMouseExited(evt);
            }
        });

        jLabelX.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabelX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelX.setText("X");

        javax.swing.GroupLayout jPanelExtLayout = new javax.swing.GroupLayout(jPanelExt);
        jPanelExt.setLayout(jPanelExtLayout);
        jPanelExtLayout.setHorizontalGroup(
            jPanelExtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelX, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );
        jPanelExtLayout.setVerticalGroup(
            jPanelExtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelX, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelBarraLayout = new javax.swing.GroupLayout(jPanelBarra);
        jPanelBarra.setLayout(jPanelBarraLayout);
        jPanelBarraLayout.setHorizontalGroup(
            jPanelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBarraLayout.createSequentialGroup()
                .addComponent(jPanelExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 769, Short.MAX_VALUE))
        );
        jPanelBarraLayout.setVerticalGroup(
            jPanelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelExt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(jPanelBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        jTextFieldusuario.setEditable(false);
        jTextFieldusuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextFieldusuario.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldusuario.setText("Ingrese su nombre de usuario");
        jTextFieldusuario.setBorder(null);
        jTextFieldusuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldusuarioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldusuarioMousePressed(evt);
            }
        });
        bg.add(jTextFieldusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 400, 20));

        jSeparatorusuario.setBackground(new java.awt.Color(0, 0, 0));
        jSeparatorusuario.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparatorusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 430, 10));

        jSeparatorconraseña.setBackground(new java.awt.Color(0, 0, 0));
        jSeparatorconraseña.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparatorconraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 430, 10));

        jLabelcontraseña.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabelcontraseña.setText("Contraseña");
        bg.add(jLabelcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jcontraseña.setEditable(false);
        jcontraseña.setFont(new java.awt.Font("MS Gothic", 0, 18)); // NOI18N
        jcontraseña.setForeground(new java.awt.Color(204, 204, 204));
        jcontraseña.setText("12345678");
        jcontraseña.setBorder(null);
        jcontraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jcontraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcontraseñaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jcontraseñaMousePressed(evt);
            }
        });
        bg.add(jcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 400, 20));

        jPanellogin.setBackground(new java.awt.Color(0, 93, 139));
        jPanellogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanellogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelloginMouseExited(evt);
            }
        });

        jLabellogin.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabellogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabellogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabellogin.setText("LOGIN");

        javax.swing.GroupLayout jPanelloginLayout = new javax.swing.GroupLayout(jPanellogin);
        jPanellogin.setLayout(jPanelloginLayout);
        jPanelloginLayout.setHorizontalGroup(
            jPanelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabellogin, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jPanelloginLayout.setVerticalGroup(
            jPanelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabellogin, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        bg.add(jPanellogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelBarraMousePressed

    private void jPanelBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraMouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelBarraMouseDragged

    private void jPanelExtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelExtMouseClicked

        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelExtMouseClicked

    private void jPanelExtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelExtMouseEntered

        jPanelExt.setBackground(Color.red);
        jLabelX.setForeground(Color.white);
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelExtMouseEntered

    private void jPanelExtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelExtMouseExited
        // TODO add your handling code here:
        jPanelExt.setBackground(new Color(255, 153, 102));
        jLabelX.setForeground(Color.BLACK);
    }//GEN-LAST:event_jPanelExtMouseExited

    private void jPanelloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelloginMouseEntered

        jPanellogin.setBackground(new Color(0, 134, 190));
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelloginMouseEntered

    private void jPanelloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelloginMouseExited
        // TODO add your handling code here:

        jPanellogin.setBackground(new Color(00, 93, 139));
    }//GEN-LAST:event_jPanelloginMouseExited

    private void jTextFieldusuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldusuarioMousePressed

        //jTextFieldusuario.setEnabled(true);
        if (jTextFieldusuario.getText().equals("Ingrese su nombre de usuario")) {
            jTextFieldusuario.setText("");
            jTextFieldusuario.setForeground(Color.black);
        }
        if (String.valueOf(jcontraseña.getPassword()).isEmpty()) {
            jcontraseña.setText("12345678");
            jcontraseña.setForeground(Color.gray);

        }
    }//GEN-LAST:event_jTextFieldusuarioMousePressed

    private void jcontraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcontraseñaMousePressed

        //jcontraseña.setEnabled(true);
        if (String.valueOf(jcontraseña.getPassword()).equals("12345678")) {
            jcontraseña.setText("");
            jcontraseña.setForeground(Color.black);
        }
        if (jTextFieldusuario.getText().isEmpty()) {
            jTextFieldusuario.setText("Ingrese su nombre de usuario");
            jTextFieldusuario.setForeground(Color.gray);

        }
    }//GEN-LAST:event_jcontraseñaMousePressed

    private void jPanelloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelloginMouseClicked

        LaEsmeraldaSanfelipe.usuario = jTextFieldusuario.getText();
        LaEsmeraldaSanfelipe.contraseña = jcontraseña.getText();
        VentanaPrincipal1 obj = new VentanaPrincipal1();
        obj.setVisible(true);
        dispose();
        JOptionPane.showMessageDialog(null, "Bienvenido: " + LaEsmeraldaSanfelipe.usuario);
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelloginMouseClicked

    private void jTextFieldusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldusuarioMouseClicked

        jTextFieldusuario.setEditable(true);
    }//GEN-LAST:event_jTextFieldusuarioMouseClicked

    private void jcontraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcontraseñaMouseClicked
        jcontraseña.setEditable(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jcontraseñaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NombreLogo;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bgcity;
    private javax.swing.JLabel bglogo;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JLabel jLabelcontraseña;
    private javax.swing.JLabel jLabellogin;
    private javax.swing.JLabel jLabellogo;
    private javax.swing.JLabel jLabelusuario;
    private javax.swing.JPanel jPanelBarra;
    private javax.swing.JPanel jPanelExt;
    public javax.swing.JPanel jPanellogin;
    private javax.swing.JSeparator jSeparatorconraseña;
    private javax.swing.JSeparator jSeparatorusuario;
    private javax.swing.JTextField jTextFieldusuario;
    private javax.swing.JPasswordField jcontraseña;
    private javax.swing.JLabel labeliniciarsesion;
    // End of variables declaration//GEN-END:variables

}
