/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laesmeraldasanfelipe;

import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.print.*;

/**
 *
 * @author Angel Feregrino
 */
public class ticket extends javax.swing.JFrame implements Printable {
public static DefaultTableModel modelticket;
    /**
     * Creates new form ticket
     */
    public ticket() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelticket = new DefaultTableModel();

        modelticket.addColumn("ID");
        modelticket.addColumn("Descripcion");
        modelticket.addColumn("Cantidad");
        modelticket.addColumn("Total");
        jTableTicket.setModel(modelticket);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTicket = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTicket = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ImporteTotal = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ImporteDescuento = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelTicket.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTicket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laesmeraldasanfelipe/img/logo.png"))); // NOI18N
        jPanelTicket.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 340, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("========================================================");
        jPanelTicket.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 340, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Portal Venustiano Carranza");
        jPanelTicket.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 340, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Colonia Centro");
        jPanelTicket.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 340, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("========================================================");
        jPanelTicket.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LA ESMERALDA");
        jPanelTicket.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 340, -1));

        jTableTicket.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jTableTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Descripcion", "Cantidad", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTableTicket);

        jPanelTicket.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 340, 140));

        jLabel12.setText("-------------------------------------------------------------------------------------");
        jPanelTicket.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 340, -1));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jLabel13.setText("Importe total");
        jPanelTicket.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        ImporteTotal.setBackground(new java.awt.Color(204, 204, 204));
        ImporteTotal.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jPanelTicket.add(ImporteTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 70, 20));

        jLabel14.setText("-------------------------------------------------------------------------------------");
        jPanelTicket.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 340, -1));

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("La elegancia aunado a la simplicidad");
        jPanelTicket.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 340, -1));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Gracias por su Preferencia! ");
        jPanelTicket.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 340, -1));

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("La Esmeralda");
        jPanelTicket.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 340, -1));

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("========================================================");
        jPanelTicket.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 340, -1));

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jLabel19.setText("Descuento %");
        jPanelTicket.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        ImporteDescuento.setBackground(new java.awt.Color(204, 204, 204));
        ImporteDescuento.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jPanelTicket.add(ImporteDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 70, 20));

        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
          PrinterJob g=PrinterJob.getPrinterJob();
          g.setPrintable(this);
          boolean gl=g.printDialog();
          if(gl){
              g.print();
          }
        }catch(PrinterException pex){
            System.out.println(pex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel ImporteDescuento;
    public static javax.swing.JLabel ImporteTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelTicket;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableTicket;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graf, PageFormat pagefor, int Index) throws PrinterException {
        if(Index>0){    
            return  NO_SUCH_PAGE;
        }
        Graphics2D ar=(Graphics2D) graf;
        ar.translate(pagefor.getImageableX() * 50, pagefor.getImageableY() * 50);
        ar.scale(1.8,1.7);
        jPanelTicket.printAll(graf);
        return PAGE_EXISTS;
    }
}
