/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laesmeraldasanfelipe;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Angel Feregrino
 */
public class VentanaDinero extends javax.swing.JFrame {

    /**
     * Creates new form VentanaVenta
     */
    public static int totalb500 = 0;
    public static int totalb200 = 0;
    public static int totalb100 = 0;
    public static int totalb50 = 0;
    public static int totalb20 = 0;
    public static int totalm10 = 0;
    public static int totalm5 = 0;
    public static int totalm2 = 0;
    public static int totalm1 = 0;

    public VentanaDinero() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    public variablesCaja dar_valores() {
        variablesCaja r = null;
        String id_cantidad = jTextFieldRetirar.getText();
        String descripcion = "CORTE DE CAJA";

        r = new variablesCaja(id_cantidad, descripcion);
        return r;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelinfo = new javax.swing.JPanel();
        jTextFieldb500 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldb200 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldb100 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldb50 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldm10 = new javax.swing.JTextField();
        jTextFieldb20 = new javax.swing.JTextField();
        jTextFieldm5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldm2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldm1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelm1 = new javax.swing.JLabel();
        jLabelb500 = new javax.swing.JLabel();
        jLabelb200 = new javax.swing.JLabel();
        jLabelb100 = new javax.swing.JLabel();
        jLabelb50 = new javax.swing.JLabel();
        jLabelb20 = new javax.swing.JLabel();
        jLabelm10 = new javax.swing.JLabel();
        jLabelm5 = new javax.swing.JLabel();
        jLabelm2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jPanelticket = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldRetirar = new javax.swing.JTextField();
        jPanelAceptar = new javax.swing.JPanel();
        jLabelAceptar = new javax.swing.JLabel();
        jPanelbarra = new javax.swing.JPanel();
        jPanelext = new javax.swing.JPanel();
        jLabelX = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelinfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dinero en Unidades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Light", 0, 11))); // NOI18N
        jPanelinfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldb500.setBorder(null);
        jTextFieldb500.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldb500MouseClicked(evt);
            }
        });
        jTextFieldb500.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldb500KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldb500KeyTyped(evt);
            }
        });
        jPanelinfo.add(jTextFieldb500, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 0, 11)); // NOI18N
        jLabel1.setText("Billetes de 500:");
        jPanelinfo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 29, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Condensed", 0, 11)); // NOI18N
        jLabel6.setText("Billetes de 200:");
        jPanelinfo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 75, -1, -1));

        jTextFieldb200.setBorder(null);
        jTextFieldb200.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldb200MouseClicked(evt);
            }
        });
        jTextFieldb200.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldb200KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldb200KeyTyped(evt);
            }
        });
        jPanelinfo.add(jTextFieldb200, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 170, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Condensed", 0, 11)); // NOI18N
        jLabel7.setText("Billetes de 100:");
        jPanelinfo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jTextFieldb100.setBorder(null);
        jTextFieldb100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldb100MouseClicked(evt);
            }
        });
        jTextFieldb100.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldb100KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldb100KeyTyped(evt);
            }
        });
        jPanelinfo.add(jTextFieldb100, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 170, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Condensed", 0, 11)); // NOI18N
        jLabel8.setText("Billetes de 50:");
        jPanelinfo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jTextFieldb50.setBorder(null);
        jTextFieldb50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldb50MouseClicked(evt);
            }
        });
        jTextFieldb50.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldb50KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldb50KeyTyped(evt);
            }
        });
        jPanelinfo.add(jTextFieldb50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 170, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Condensed", 0, 11)); // NOI18N
        jLabel9.setText("Monedas de 10:");
        jPanelinfo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel12.setFont(new java.awt.Font("Roboto Condensed", 0, 11)); // NOI18N
        jLabel12.setText("Billetes de 20:");
        jPanelinfo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jTextFieldm10.setBorder(null);
        jTextFieldm10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldm10MouseClicked(evt);
            }
        });
        jTextFieldm10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldm10KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldm10KeyTyped(evt);
            }
        });
        jPanelinfo.add(jTextFieldm10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 170, -1));

        jTextFieldb20.setBorder(null);
        jTextFieldb20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldb20MouseClicked(evt);
            }
        });
        jTextFieldb20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldb20KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldb20KeyTyped(evt);
            }
        });
        jPanelinfo.add(jTextFieldb20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 170, -1));

        jTextFieldm5.setBorder(null);
        jTextFieldm5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldm5MouseClicked(evt);
            }
        });
        jTextFieldm5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldm5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldm5KeyTyped(evt);
            }
        });
        jPanelinfo.add(jTextFieldm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 170, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Condensed", 0, 11)); // NOI18N
        jLabel10.setText("Monedas de 5:");
        jPanelinfo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jTextFieldm2.setBorder(null);
        jTextFieldm2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldm2MouseClicked(evt);
            }
        });
        jTextFieldm2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldm2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldm2KeyTyped(evt);
            }
        });
        jPanelinfo.add(jTextFieldm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 170, -1));

        jLabel13.setFont(new java.awt.Font("Roboto Condensed", 0, 11)); // NOI18N
        jLabel13.setText("Monedas de 2:");
        jPanelinfo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jTextFieldm1.setBorder(null);
        jTextFieldm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldm1MouseClicked(evt);
            }
        });
        jTextFieldm1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldm1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldm1KeyTyped(evt);
            }
        });
        jPanelinfo.add(jTextFieldm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 170, -1));

        jLabel14.setFont(new java.awt.Font("Roboto Condensed", 0, 11)); // NOI18N
        jLabel14.setText("Monedas de 1:");
        jPanelinfo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Total:");
        jPanelinfo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabelm1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabelm1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelm1.setText("0");
        jPanelinfo.add(jLabelm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 140, -1));

        jLabelb500.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabelb500.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelb500.setText("0");
        jPanelinfo.add(jLabelb500, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 140, -1));

        jLabelb200.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabelb200.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelb200.setText("0");
        jPanelinfo.add(jLabelb200, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 140, -1));

        jLabelb100.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabelb100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelb100.setText("0");
        jPanelinfo.add(jLabelb100, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 140, -1));

        jLabelb50.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabelb50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelb50.setText("0");
        jPanelinfo.add(jLabelb50, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 140, -1));

        jLabelb20.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabelb20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelb20.setText("0");
        jPanelinfo.add(jLabelb20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 140, -1));

        jLabelm10.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabelm10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelm10.setText("0");
        jPanelinfo.add(jLabelm10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 140, -1));

        jLabelm5.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabelm5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelm5.setText("0");
        jPanelinfo.add(jLabelm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 140, -1));

        jLabelm2.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabelm2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelm2.setText("0");
        jPanelinfo.add(jLabelm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 140, -1));
        jPanelinfo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 380, 10));
        jPanelinfo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 380, 10));
        jPanelinfo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 380, 10));
        jPanelinfo.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 380, 10));
        jPanelinfo.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 380, 10));
        jPanelinfo.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 380, 10));
        jPanelinfo.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 380, 10));
        jPanelinfo.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 380, 10));
        jPanelinfo.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 380, 10));

        jPanel1.add(jPanelinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 380, 490));

        jPanelticket.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelticket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Total");
        jPanelticket.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 320, -1));

        jLabelTotal.setFont(new java.awt.Font("Roboto Condensed", 1, 36)); // NOI18N
        jLabelTotal.setForeground(new java.awt.Color(0, 0, 255));
        jLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotal.setText("0");
        jPanelticket.add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 320, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 3, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Dinero a Retirar:");
        jPanelticket.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 320, -1));

        jTextFieldRetirar.setText("0");
        jTextFieldRetirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldRetirarMouseClicked(evt);
            }
        });
        jTextFieldRetirar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRetirarKeyTyped(evt);
            }
        });
        jPanelticket.add(jTextFieldRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 160, -1));

        jPanelAceptar.setBackground(new java.awt.Color(255, 255, 0));
        jPanelAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAceptarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAceptarMouseExited(evt);
            }
        });

        jLabelAceptar.setFont(new java.awt.Font("Roboto Thin", 3, 14)); // NOI18N
        jLabelAceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laesmeraldasanfelipe/img/aceptar.png"))); // NOI18N
        jLabelAceptar.setText("Cerrar Corte");

        javax.swing.GroupLayout jPanelAceptarLayout = new javax.swing.GroupLayout(jPanelAceptar);
        jPanelAceptar.setLayout(jPanelAceptarLayout);
        jPanelAceptarLayout.setHorizontalGroup(
            jPanelAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelAceptarLayout.setVerticalGroup(
            jPanelAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelticket.add(jPanelAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 130, 50));

        jPanel1.add(jPanelticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 320, 240));

        jPanelbarra.setBackground(new java.awt.Color(255, 153, 102));
        jPanelbarra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelbarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelext.setBackground(new java.awt.Color(255, 153, 102));
        jPanelext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelextMouseExited(evt);
            }
        });

        jLabelX.setBackground(new java.awt.Color(255, 255, 255));
        jLabelX.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabelX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelX.setText("X");

        javax.swing.GroupLayout jPanelextLayout = new javax.swing.GroupLayout(jPanelext);
        jPanelext.setLayout(jPanelextLayout);
        jPanelextLayout.setHorizontalGroup(
            jPanelextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelX, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        jPanelextLayout.setVerticalGroup(
            jPanelextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelbarra.add(jPanelext, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Corte de Caja");
        jPanelbarra.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        jPanel1.add(jPanelbarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 30));

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 110, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelextMouseClicked
        dispose();
    }//GEN-LAST:event_jPanelextMouseClicked

    private void jPanelextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelextMouseEntered
        jPanelext.setBackground(Color.red);
        jLabelX.setForeground(Color.white);
    }//GEN-LAST:event_jPanelextMouseEntered

    private void jPanelextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelextMouseExited
        jPanelext.setBackground(new Color(255, 153, 102));
        jLabelX.setForeground(Color.BLACK);
    }//GEN-LAST:event_jPanelextMouseExited

    private void jTextFieldRetirarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRetirarKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (jTextFieldRetirar.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldRetirarKeyTyped

    private void jPanelAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAceptarMouseEntered
        jPanelAceptar.setBackground(Color.red);
        jLabelAceptar.setForeground(Color.white);
    }//GEN-LAST:event_jPanelAceptarMouseEntered

    private void jPanelAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAceptarMouseExited
        jPanelAceptar.setBackground(Color.yellow);
        jLabelAceptar.setForeground(Color.BLACK);
    }//GEN-LAST:event_jPanelAceptarMouseExited

    private void jPanelAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAceptarMouseClicked
        variablesCaja x = null;
        x = dar_valores();
        try {
            Conexion.SalidaCaja(x);
        } catch (SQLException ex) {
            Logger.getLogger(Caja.class.getName()).log(Level.SEVERE, null, ex);
        }
        Conexion.mostrarCaja(Caja.jTable1);

        dispose();

    }//GEN-LAST:event_jPanelAceptarMouseClicked

    private void jTextFieldm10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldm10KeyTyped

        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (jTextFieldm10.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldm10KeyTyped

    private void jTextFieldm5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldm5KeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (jTextFieldm5.getText().trim().length() == 10) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldm5KeyTyped

    private void jTextFieldm2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldm2KeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (jTextFieldm2.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldm2KeyTyped

    private void jTextFieldm1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldm1KeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (jTextFieldm1.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldm1KeyTyped

    private void jTextFieldb500KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldb500KeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (jTextFieldb500.getText().trim().length() == 10) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldb500KeyTyped

    private void jTextFieldb200KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldb200KeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (jTextFieldb200.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldb200KeyTyped

    private void jTextFieldb100KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldb100KeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (jTextFieldb100.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldb100KeyTyped

    private void jTextFieldb50KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldb50KeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (jTextFieldb50.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldb50KeyTyped

    private void jTextFieldb20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldb20KeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (jTextFieldb20.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldb20KeyTyped

    private void jTextFieldb500KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldb500KeyReleased
        if (jTextFieldb500.getText().isEmpty()) {
        }
        String billetes500 = jTextFieldb500.getText();
        int b500 = Integer.parseInt(billetes500);
        totalb500 = b500 * 500;
        String mostrartotal = String.valueOf(totalb500);
        jLabelb500.setText(mostrartotal);

        int total = totalb500 + totalb200 + totalb100 + totalb50 + totalb20 + totalm10 + totalm5 + totalm2 + totalm1;
        String mostrartotalfinal = String.valueOf(total);
        jLabelTotal.setText(mostrartotalfinal);

    }//GEN-LAST:event_jTextFieldb500KeyReleased

    private void jTextFieldb200KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldb200KeyReleased
        if (jTextFieldb200.getText().isEmpty()) {
            
        }
        String billetes200 = jTextFieldb200.getText();
        int b200 = Integer.parseInt(billetes200);
        totalb200 = b200 * 200;
        String mostrartotal = String.valueOf(totalb200);
        jLabelb200.setText(mostrartotal);

        int total = totalb500 + totalb200 + totalb100 + totalb50 + totalb20 + totalm10 + totalm5 + totalm2 + totalm1;
        String mostrartotalfinal = String.valueOf(total);
        jLabelTotal.setText(mostrartotalfinal);
    }//GEN-LAST:event_jTextFieldb200KeyReleased

    private void jTextFieldb100KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldb100KeyReleased
        if (jTextFieldb100.getText().isEmpty()) {
            
        }
        String billetes100 = jTextFieldb100.getText();
        int b100 = Integer.parseInt(billetes100);
        totalb100 = b100 * 100;
        String mostrartotal = String.valueOf(totalb100);
        jLabelb100.setText(mostrartotal);

        int total = totalb500 + totalb200 + totalb100 + totalb50 + totalb20 + totalm10 + totalm5 + totalm2 + totalm1;
        String mostrartotalfinal = String.valueOf(total);
        jLabelTotal.setText(mostrartotalfinal);
    }//GEN-LAST:event_jTextFieldb100KeyReleased

    private void jTextFieldb50KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldb50KeyReleased
        if (jTextFieldb50.getText().isEmpty()) {
            
        }
        String billetes50 = jTextFieldb50.getText();
        int b50 = Integer.parseInt(billetes50);
        totalb50 = b50 * 50;
        String mostrartotal = String.valueOf(totalb50);
        jLabelb50.setText(mostrartotal);

        int total = totalb500 + totalb200 + totalb100 + totalb50 + totalb20 + totalm10 + totalm5 + totalm2 + totalm1;
        String mostrartotalfinal = String.valueOf(total);
        jLabelTotal.setText(mostrartotalfinal);
    }//GEN-LAST:event_jTextFieldb50KeyReleased

    private void jTextFieldb20KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldb20KeyReleased
        if (jTextFieldb20.getText().isEmpty()) {
        }
        String billetes20 = jTextFieldb20.getText();
        int b20 = Integer.parseInt(billetes20);
        totalb20 = b20 * 20;
        String mostrartotal = String.valueOf(totalb20);
        jLabelb20.setText(mostrartotal);

        int total = totalb500 + totalb200 + totalb100 + totalb50 + totalb20 + totalm10 + totalm5 + totalm2 + totalm1;
        String mostrartotalfinal = String.valueOf(total);
        jLabelTotal.setText(mostrartotalfinal);
    }//GEN-LAST:event_jTextFieldb20KeyReleased

    private void jTextFieldm10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldm10KeyReleased
        if (jTextFieldm10.getText().isEmpty()) {
        }
        String monedas10 = jTextFieldm10.getText();
        int m10 = Integer.parseInt(monedas10);
        totalm10 = m10 * 10;
        String mostrartotal = String.valueOf(totalm10);
        jLabelm10.setText(mostrartotal);

        int total = totalb500 + totalb200 + totalb100 + totalb50 + totalb20 + totalm10 + totalm5 + totalm2 + totalm1;
        String mostrartotalfinal = String.valueOf(total);
        jLabelTotal.setText(mostrartotalfinal);
    }//GEN-LAST:event_jTextFieldm10KeyReleased

    private void jTextFieldm5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldm5KeyReleased
        if (jTextFieldm5.getText().isEmpty()) {
        }
        String monedas5 = jTextFieldm5.getText();
        int m5 = Integer.parseInt(monedas5);
        totalm5 = m5 * 5;
        String mostrartotal = String.valueOf(totalm5);
        jLabelm5.setText(mostrartotal);

        int total = totalb500 + totalb200 + totalb100 + totalb50 + totalb20 + totalm10 + totalm5 + totalm2 + totalm1;
        String mostrartotalfinal = String.valueOf(total);
        jLabelTotal.setText(mostrartotalfinal);
    }//GEN-LAST:event_jTextFieldm5KeyReleased

    private void jTextFieldm2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldm2KeyReleased
        if (jTextFieldm2.getText().isEmpty()) {
        }
        String monedas2 = jTextFieldm2.getText();
        int m2 = Integer.parseInt(monedas2);
        totalm2 = m2 * 2;
        String mostrartotal = String.valueOf(totalm2);
        jLabelm2.setText(mostrartotal);

        int total = totalb500 + totalb200 + totalb100 + totalb50 + totalb20 + totalm10 + totalm5 + totalm2 + totalm1;
        String mostrartotalfinal = String.valueOf(total);
        jLabelTotal.setText(mostrartotalfinal);
    }//GEN-LAST:event_jTextFieldm2KeyReleased

    private void jTextFieldm1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldm1KeyReleased
        if (jTextFieldm1.getText().isEmpty()) {
        }
        String monedas1 = jTextFieldm1.getText();
        int m1 = Integer.parseInt(monedas1);
        totalm1 = m1 * 1;
        String mostrartotal = String.valueOf(totalm1);
        jLabelm1.setText(mostrartotal);

        int total = totalb500 + totalb200 + totalb100 + totalb50 + totalb20 + totalm10 + totalm5 + totalm2 + totalm1;
        String mostrartotalfinal = String.valueOf(total);
        jLabelTotal.setText(mostrartotalfinal);
    }//GEN-LAST:event_jTextFieldm1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String set = "0";
        jTextFieldb100.setText(set);
        jTextFieldb20.setText(set);
        jTextFieldb200.setText(set);
        jTextFieldb50.setText(set);
        jTextFieldb500.setText(set);
        jTextFieldm1.setText(set);
        jTextFieldm10.setText(set);
        jTextFieldm2.setText(set);
        jTextFieldm5.setText(set);
        jLabelb500.setText(set);
        jLabelb200.setText(set);
        jLabelb100.setText(set);
        jLabelb50.setText(set);
        jLabelb20.setText(set);
        jLabelm10.setText(set);
        jLabelm5.setText(set);
        jLabelm2.setText(set);
        jLabelm1.setText(set);
        jLabelTotal.setText(set);
        totalb500 = 0;
        totalb200 = 0;
        totalb100 = 0;
        totalb50 = 0;
        totalb20 = 0;
        totalm10 = 0;
        totalm5 = 0;
        totalm2 = 0;
        totalm1 = 0;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldb500MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldb500MouseClicked
        jTextFieldb500.setText("");
    }//GEN-LAST:event_jTextFieldb500MouseClicked

    private void jTextFieldb200MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldb200MouseClicked
        jTextFieldb200.setText("");
    }//GEN-LAST:event_jTextFieldb200MouseClicked

    private void jTextFieldb100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldb100MouseClicked
        jTextFieldb100.setText("");
    }//GEN-LAST:event_jTextFieldb100MouseClicked

    private void jTextFieldb50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldb50MouseClicked
        jTextFieldb50.setText("");
    }//GEN-LAST:event_jTextFieldb50MouseClicked

    private void jTextFieldb20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldb20MouseClicked
        jTextFieldb20.setText("");
    }//GEN-LAST:event_jTextFieldb20MouseClicked

    private void jTextFieldm10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldm10MouseClicked
        jTextFieldm10.setText("");
    }//GEN-LAST:event_jTextFieldm10MouseClicked

    private void jTextFieldm5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldm5MouseClicked
        jTextFieldm5.setText("");
    }//GEN-LAST:event_jTextFieldm5MouseClicked

    private void jTextFieldm2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldm2MouseClicked
        jTextFieldm2.setText("");
    }//GEN-LAST:event_jTextFieldm2MouseClicked

    private void jTextFieldm1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldm1MouseClicked
        jTextFieldm1.setText("");
    }//GEN-LAST:event_jTextFieldm1MouseClicked

    private void jTextFieldRetirarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldRetirarMouseClicked
        jTextFieldRetirar.setText("");
    }//GEN-LAST:event_jTextFieldRetirarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDinero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAceptar;
    public static javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JLabel jLabelb100;
    private javax.swing.JLabel jLabelb20;
    private javax.swing.JLabel jLabelb200;
    private javax.swing.JLabel jLabelb50;
    private javax.swing.JLabel jLabelb500;
    private javax.swing.JLabel jLabelm1;
    private javax.swing.JLabel jLabelm10;
    private javax.swing.JLabel jLabelm2;
    private javax.swing.JLabel jLabelm5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAceptar;
    private javax.swing.JPanel jPanelbarra;
    private javax.swing.JPanel jPanelext;
    private javax.swing.JPanel jPanelinfo;
    private javax.swing.JPanel jPanelticket;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextFieldRetirar;
    public static javax.swing.JTextField jTextFieldb100;
    public static javax.swing.JTextField jTextFieldb20;
    public static javax.swing.JTextField jTextFieldb200;
    public static javax.swing.JTextField jTextFieldb50;
    public static javax.swing.JTextField jTextFieldb500;
    public static javax.swing.JTextField jTextFieldm1;
    public static javax.swing.JTextField jTextFieldm10;
    public static javax.swing.JTextField jTextFieldm2;
    public static javax.swing.JTextField jTextFieldm5;
    // End of variables declaration//GEN-END:variables

}
