/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laesmeraldasanfelipe;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Angel Feregrino
 */
public class VentanaVentaFinal extends javax.swing.JFrame {

    public static DefaultTableModel model2;
    /**
     * Creates new form VentanaVenta
     */
    public static String recibido1;
    public static int descuento;
    public static int totalmente = 0;

    public VentanaVentaFinal() {
        initComponents();
        this.setLocationRelativeTo(null);
        SalidaFinal.mostrartotal = jLabelTotal.getText();
        model2 = new DefaultTableModel();

        model2.addColumn("Producto ID");
        model2.addColumn("Nombre");
        model2.addColumn("Descripcion");
        model2.addColumn("Codigo");
        model2.addColumn("Cantidad");
        model2.addColumn("Precio");
        model2.addColumn("Fecha");
        jTableArticulos.setModel(model2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelticket = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelCambio = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldRecibido = new javax.swing.JTextField();
        jPanelTicket = new javax.swing.JPanel();
        jLabelTicket = new javax.swing.JLabel();
        jPanelAceptar1 = new javax.swing.JPanel();
        jLabelAceptar1 = new javax.swing.JLabel();
        jPanelbarra = new javax.swing.JPanel();
        jPanelext = new javax.swing.JPanel();
        jLabelX = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableArticulos = new javax.swing.JTable();
        jTextFieldDescuento = new javax.swing.JTextField();
        jPanelDescuento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 93, 139));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelticket.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelticket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Total a Pagar");
        jPanelticket.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 400, -1));

        jLabelTotal.setFont(new java.awt.Font("Roboto Condensed", 1, 36)); // NOI18N
        jLabelTotal.setForeground(new java.awt.Color(0, 0, 255));
        jLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotal.setText(" ");
        jPanelticket.add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 40, 400, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 3, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Dinero Recibido:");
        jPanelticket.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 110, 390, -1));

        jLabelCambio.setFont(new java.awt.Font("Roboto Condensed", 1, 36)); // NOI18N
        jLabelCambio.setForeground(new java.awt.Color(0, 0, 255));
        jLabelCambio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCambio.setText(" ");
        jPanelticket.add(jLabelCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 400, -1));

        jLabel11.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Cambio");
        jPanelticket.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 400, -1));

        jTextFieldRecibido.setText("0");
        jTextFieldRecibido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldRecibidoMouseClicked(evt);
            }
        });
        jTextFieldRecibido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldRecibidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRecibidoKeyTyped(evt);
            }
        });
        jPanelticket.add(jTextFieldRecibido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 150, -1));

        jPanelTicket.setBackground(new java.awt.Color(255, 255, 0));
        jPanelTicket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelTicketMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelTicketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelTicketMouseExited(evt);
            }
        });

        jLabelTicket.setFont(new java.awt.Font("Roboto Thin", 3, 14)); // NOI18N
        jLabelTicket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laesmeraldasanfelipe/img/ticket.png"))); // NOI18N
        jLabelTicket.setText("Imprimir Ticket");

        javax.swing.GroupLayout jPanelTicketLayout = new javax.swing.GroupLayout(jPanelTicket);
        jPanelTicket.setLayout(jPanelTicketLayout);
        jPanelTicketLayout.setHorizontalGroup(
            jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelTicketLayout.setVerticalGroup(
            jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTicket, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelticket.add(jPanelTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 150, 50));

        jPanelAceptar1.setBackground(new java.awt.Color(255, 255, 0));
        jPanelAceptar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelAceptar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAceptar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAceptar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAceptar1MouseExited(evt);
            }
        });

        jLabelAceptar1.setFont(new java.awt.Font("Roboto Thin", 3, 14)); // NOI18N
        jLabelAceptar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAceptar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laesmeraldasanfelipe/img/aceptar.png"))); // NOI18N
        jLabelAceptar1.setText("Aceptar");

        javax.swing.GroupLayout jPanelAceptar1Layout = new javax.swing.GroupLayout(jPanelAceptar1);
        jPanelAceptar1.setLayout(jPanelAceptar1Layout);
        jPanelAceptar1Layout.setHorizontalGroup(
            jPanelAceptar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAceptar1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanelAceptar1Layout.setVerticalGroup(
            jPanelAceptar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAceptar1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelticket.add(jPanelAceptar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jPanel1.add(jPanelticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 410, 340));

        jPanelbarra.setBackground(new java.awt.Color(255, 153, 102));
        jPanelbarra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelbarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelext.setBackground(new java.awt.Color(255, 153, 102));
        jPanelext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelextMouseExited(evt);
            }
        });

        jLabelX.setBackground(new java.awt.Color(255, 255, 255));
        jLabelX.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabelX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelX.setText("X");

        javax.swing.GroupLayout jPanelextLayout = new javax.swing.GroupLayout(jPanelext);
        jPanelext.setLayout(jPanelextLayout);
        jPanelextLayout.setHorizontalGroup(
            jPanelextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelX, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        jPanelextLayout.setVerticalGroup(
            jPanelextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelbarra.add(jPanelext, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ticket");
        jPanelbarra.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        jPanel1.add(jPanelbarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 30));

        jPanelTabla.setBorder(javax.swing.BorderFactory.createTitledBorder("Articulos"));

        jTableArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto ID", "Nombre", "Descripcion", "Codigo", "Cantidad", "Precio", "Fecha"
            }
        ));
        jTableArticulos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableArticulosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableArticulos);

        javax.swing.GroupLayout jPanelTablaLayout = new javax.swing.GroupLayout(jPanelTabla);
        jPanelTabla.setLayout(jPanelTablaLayout);
        jPanelTablaLayout.setHorizontalGroup(
            jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        jPanelTablaLayout.setVerticalGroup(
            jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 620, 170));

        jTextFieldDescuento.setFont(new java.awt.Font("Roboto Thin", 1, 14)); // NOI18N
        jTextFieldDescuento.setText("0");
        jTextFieldDescuento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldDescuentoMouseClicked(evt);
            }
        });
        jTextFieldDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDescuentoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDescuentoKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 120, -1));

        jPanelDescuento.setBackground(new java.awt.Color(102, 204, 255));
        jPanelDescuento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelDescuento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelDescuentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelDescuentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelDescuentoMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Thin", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Descuento %");

        javax.swing.GroupLayout jPanelDescuentoLayout = new javax.swing.GroupLayout(jPanelDescuento);
        jPanelDescuento.setLayout(jPanelDescuentoLayout);
        jPanelDescuentoLayout.setHorizontalGroup(
            jPanelDescuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanelDescuentoLayout.setVerticalGroup(
            jPanelDescuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 120, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelextMouseClicked
        dispose();
        evt.consume();
    }//GEN-LAST:event_jPanelextMouseClicked

    private void jPanelextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelextMouseEntered
        jPanelext.setBackground(Color.red);
        jLabelX.setForeground(Color.white);
        evt.consume();
    }//GEN-LAST:event_jPanelextMouseEntered

    private void jPanelextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelextMouseExited
        jPanelext.setBackground(new Color(255, 153, 102));
        jLabelX.setForeground(Color.BLACK);
        evt.consume();
    }//GEN-LAST:event_jPanelextMouseExited

    private void jTextFieldRecibidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRecibidoKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (jTextFieldRecibido.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldRecibidoKeyTyped

    private void jPanelTicketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTicketMouseEntered
        jPanelTicket.setBackground(Color.red);
        jLabelTicket.setForeground(Color.white);
        evt.consume();
    }//GEN-LAST:event_jPanelTicketMouseEntered

    private void jPanelTicketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTicketMouseExited
        jPanelTicket.setBackground(Color.yellow);
        jLabelTicket.setForeground(Color.BLACK);
        evt.consume();
    }//GEN-LAST:event_jPanelTicketMouseExited

    private void jPanelTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTicketMouseClicked
        
        ticket obj = new ticket();
        obj.setVisible(true);
        for (int i = 0; i < jTableArticulos.getRowCount(); i++) {
            String fila[] = new String[7];
            fila[0] = jTableArticulos.getValueAt(i, 0).toString();
            fila[1] = jTableArticulos.getValueAt(i, 2).toString();
            fila[2] = jTableArticulos.getValueAt(i, 4).toString();
            fila[3] = jTableArticulos.getValueAt(i, 5).toString();
            

            ticket.modelticket.addRow(fila);
        }
        String importe=jLabelTotal.getText();
        ticket.ImporteTotal.setText(importe);
        ticket.ImporteDescuento.setText(jTextFieldDescuento.getText());
                
        

    }//GEN-LAST:event_jPanelTicketMouseClicked

    private void jTextFieldRecibidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRecibidoKeyReleased
        if (jTextFieldRecibido.getText().isEmpty()) {
            jTextFieldRecibido.setText("0");
            recibido1 = "0";
        }
        recibido1 = jTextFieldRecibido.getText();

        int totalmente = Integer.parseInt(SalidaFinal.mostrartotal);
        int recibido = Integer.parseInt(recibido1);
        int cambio = recibido - totalmente;
        String mostrarcambio = String.valueOf(cambio);
        jLabelCambio.setText("$ " + mostrarcambio);
        evt.consume();
    }//GEN-LAST:event_jTextFieldRecibidoKeyReleased

    private void jTextFieldRecibidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldRecibidoMouseClicked
        jTextFieldRecibido.setText("");
        evt.consume();
    }//GEN-LAST:event_jTextFieldRecibidoMouseClicked

    private void jPanelAceptar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAceptar1MouseClicked

        int fila = jTableArticulos.getRowCount();
        for (int i = 0; i < fila; i++) {

            try {
                
                String ProductoID = (String) jTableArticulos.getValueAt(i, 0);
                String Fecha = (String) jTableArticulos.getValueAt(i, 6);
                String preciototal = (String) jTableArticulos.getValueAt(i, 5);
                String Cantidad = (String) jTableArticulos.getValueAt(i, 4);

                String q = "INSERT INTO `salida`(`id_salida`, `salida_producto_id`, `salida_fecha`, `salida_cantidad`) VALUES ('NULL','" + ProductoID + "','" + Fecha + "','" + Cantidad + "')";
                String sumaS = "SELECT SUM(entrada) FROM caja;";
                String restaS = "SELECT SUM(salida) FROM caja;";
                Conexion.ejecutar(q);
                int preciototalint = Integer.parseInt(preciototal);
                int suma = Conexion.ejecutar2(sumaS);
                int resta = Conexion.ejecutar2(restaS);
                int totalsql = preciototalint + suma;
                int totalfinal = totalsql - resta;
                String total2 = String.valueOf(preciototalint);
                String totalfinal2 = String.valueOf(totalfinal);
                String cajaentrada = "INSERT INTO `caja`(`id_transaccion`, `entrada`, `salida`, `total`, `descripcion`)"
                        + "VALUES ('NULL','" + total2 + "','0','" + totalfinal2 + "','Ventas')";
                Conexion.ejecutar(cajaentrada);

            } catch (SQLException ex) {
                Logger.getLogger(VentanaVentaFinal.class.getName()).log(Level.SEVERE, null, ex);
            }
            DefaultTableModel dm = (DefaultTableModel) SalidaFinal.jTable1.getModel();
            while (dm.getRowCount() > 0) {
                dm.removeRow(0);
            }

            dispose();
        }
    }//GEN-LAST:event_jPanelAceptar1MouseClicked

    private void jPanelAceptar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAceptar1MouseEntered
        jPanelAceptar1.setBackground(Color.red);
        jLabelAceptar1.setForeground(Color.white);
        evt.consume();
    }//GEN-LAST:event_jPanelAceptar1MouseEntered

    private void jPanelAceptar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAceptar1MouseExited
        jPanelAceptar1.setBackground(Color.yellow);
        jLabelAceptar1.setForeground(Color.BLACK);
        evt.consume();
    }//GEN-LAST:event_jPanelAceptar1MouseExited

    private void jTextFieldDescuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescuentoKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (jTextFieldDescuento.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldDescuentoKeyTyped

    private void jPanelDescuentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDescuentoMouseClicked
        SalidaFinal.mostrartotal = "0";
        for (int i = 0; i < jTableArticulos.getRowCount(); i++) {
            String precio = (String) jTableArticulos.getValueAt(i, 5);

            double precioint = Double.parseDouble(precio);

            double decimal = Integer.parseInt(jTextFieldDescuento.getText());

            double decimaldescuento = decimal / 100;

            double descuento = (precioint - (precioint * decimaldescuento));

            int descuentoint = (int) descuento;
            String descuentostring = String.valueOf(descuentoint);

            jTableArticulos.setValueAt(descuentostring, i, 5);

        }
        for (int i = 0; i < jTableArticulos.getRowCount(); i++) {

            String precio = (String) jTableArticulos.getValueAt(i, 5);
            int precioint = Integer.parseInt(precio);
            int totalmente = Integer.parseInt(SalidaFinal.mostrartotal);
            totalmente = totalmente + precioint;

            SalidaFinal.mostrartotal = String.valueOf(totalmente);
        }

        jLabelTotal.setText("$ " + SalidaFinal.mostrartotal);

        evt.consume();

    }//GEN-LAST:event_jPanelDescuentoMouseClicked

    private void jPanelDescuentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDescuentoMouseEntered
        jPanelDescuento.setBackground(new Color(0, 134, 190));
        evt.consume();
    }//GEN-LAST:event_jPanelDescuentoMouseEntered

    private void jPanelDescuentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDescuentoMouseExited
        jPanelDescuento.setBackground(new Color(102, 204, 255));
        evt.consume();
    }//GEN-LAST:event_jPanelDescuentoMouseExited

    private void jTableArticulosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableArticulosKeyReleased
        SalidaFinal.mostrartotal = "0";
        for (int i = 0; i < jTableArticulos.getRowCount(); i++) {

            String precio = (String) jTableArticulos.getValueAt(i, 5);
            int precioint = Integer.parseInt(precio);
            int totalmente = Integer.parseInt(SalidaFinal.mostrartotal);
            totalmente = totalmente + precioint;

            SalidaFinal.mostrartotal = String.valueOf(totalmente);
        }

        jLabelTotal.setText("$ " + SalidaFinal.mostrartotal);

        evt.consume();

    }//GEN-LAST:event_jTableArticulosKeyReleased

    private void jTextFieldDescuentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescuentoKeyReleased
        if(jTextFieldDescuento.getText().isEmpty()){
            jTextFieldDescuento.setText("0");
        }
    }//GEN-LAST:event_jTextFieldDescuentoKeyReleased

    private void jTextFieldDescuentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldDescuentoMouseClicked
        jTextFieldDescuento.setText("");
    }//GEN-LAST:event_jTextFieldDescuentoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVentaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVentaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVentaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVentaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VentanaVentaFinal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAceptar1;
    private javax.swing.JLabel jLabelCambio;
    private javax.swing.JLabel jLabelTicket;
    public static javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAceptar1;
    private javax.swing.JPanel jPanelDescuento;
    private javax.swing.JPanel jPanelTabla;
    private javax.swing.JPanel jPanelTicket;
    private javax.swing.JPanel jPanelbarra;
    private javax.swing.JPanel jPanelext;
    private javax.swing.JPanel jPanelticket;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableArticulos;
    private javax.swing.JTextField jTextFieldDescuento;
    private javax.swing.JTextField jTextFieldRecibido;
    // End of variables declaration//GEN-END:variables

}
