package laesmeraldasanfelipe;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author luisa
 */
public class VentanaPrincipal1 extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    int xMouse, yMouse;
    public static String administrador;

    public VentanaPrincipal1() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        Conexion.Conectar();
        tiempo();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/laesmeraldasanfelipe/img/icono.png")));
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelbarra = new javax.swing.JPanel();
        jPanelext = new javax.swing.JPanel();
        jLabelX = new javax.swing.JLabel();
        jPanelmin = new javax.swing.JPanel();
        jLabelM = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botonRegistroInventario = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        botonInventario = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        botonProductos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        botonVentas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        botonCliente = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        botonCaja = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        botonRespaldos1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        botonReporteVentas = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        botonRespaldos = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabelfecha = new javax.swing.JLabel();
        contenedor = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("La Esmeralda");
        setBackground(new java.awt.Color(0, 102, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelbarra.setBackground(new java.awt.Color(255, 153, 102));
        jPanelbarra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelbarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelbarraMouseDragged(evt);
            }
        });
        jPanelbarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelbarraMousePressed(evt);
            }
        });
        jPanelbarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelext.setBackground(new java.awt.Color(255, 153, 102));
        jPanelext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelextMouseExited(evt);
            }
        });

        jLabelX.setBackground(new java.awt.Color(255, 255, 255));
        jLabelX.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabelX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelX.setText("X");

        javax.swing.GroupLayout jPanelextLayout = new javax.swing.GroupLayout(jPanelext);
        jPanelext.setLayout(jPanelextLayout);
        jPanelextLayout.setHorizontalGroup(
            jPanelextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelX, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        jPanelextLayout.setVerticalGroup(
            jPanelextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelbarra.add(jPanelext, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jPanelmin.setBackground(new java.awt.Color(255, 153, 102));
        jPanelmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelminMouseExited(evt);
            }
        });

        jLabelM.setBackground(new java.awt.Color(255, 153, 102));
        jLabelM.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabelM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laesmeraldasanfelipe/img/minimizar25.png"))); // NOI18N

        javax.swing.GroupLayout jPanelminLayout = new javax.swing.GroupLayout(jPanelmin);
        jPanelmin.setLayout(jPanelminLayout);
        jPanelminLayout.setHorizontalGroup(
            jPanelminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelminLayout.createSequentialGroup()
                .addComponent(jLabelM, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        jPanelminLayout.setVerticalGroup(
            jPanelminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelbarra.add(jPanelmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 30));

        jPanel1.add(jPanelbarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 30));

        jPanel3.setBackground(new java.awt.Color(0, 93, 139));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laesmeraldasanfelipe/img/imagelogin-removebg-preview.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 250, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LA ESMERALDA");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 204, 250, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 188, 220, 10));

        botonRegistroInventario.setBackground(new java.awt.Color(0, 93, 139));
        botonRegistroInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistroInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistroInventarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegistroInventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegistroInventarioMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laesmeraldasanfelipe/img/Registroinventario.png"))); // NOI18N
        jLabel4.setText("Registro de Inventarios");

        javax.swing.GroupLayout botonRegistroInventarioLayout = new javax.swing.GroupLayout(botonRegistroInventario);
        botonRegistroInventario.setLayout(botonRegistroInventarioLayout);
        botonRegistroInventarioLayout.setHorizontalGroup(
            botonRegistroInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        botonRegistroInventarioLayout.setVerticalGroup(
            botonRegistroInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(botonRegistroInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 250, 40));

        botonInventario.setBackground(new java.awt.Color(0, 93, 139));
        botonInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInventarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonInventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonInventarioMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laesmeraldasanfelipe/img/inventario.png"))); // NOI18N
        jLabel5.setText("Inventario");

        javax.swing.GroupLayout botonInventarioLayout = new javax.swing.GroupLayout(botonInventario);
        botonInventario.setLayout(botonInventarioLayout);
        botonInventarioLayout.setHorizontalGroup(
            botonInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        botonInventarioLayout.setVerticalGroup(
            botonInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(botonInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 250, -1));

        botonProductos.setBackground(new java.awt.Color(0, 93, 139));
        botonProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonProductosMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laesmeraldasanfelipe/img/productos.png"))); // NOI18N
        jLabel6.setText("Entrada de Inventario");

        javax.swing.GroupLayout botonProductosLayout = new javax.swing.GroupLayout(botonProductos);
        botonProductos.setLayout(botonProductosLayout);
        botonProductosLayout.setHorizontalGroup(
            botonProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        botonProductosLayout.setVerticalGroup(
            botonProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(botonProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 250, -1));

        botonVentas.setBackground(new java.awt.Color(0, 93, 139));
        botonVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonVentasMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laesmeraldasanfelipe/img/ventas.png"))); // NOI18N
        jLabel7.setText("Ventas");

        javax.swing.GroupLayout botonVentasLayout = new javax.swing.GroupLayout(botonVentas);
        botonVentas.setLayout(botonVentasLayout);
        botonVentasLayout.setHorizontalGroup(
            botonVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        botonVentasLayout.setVerticalGroup(
            botonVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(botonVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 250, -1));

        botonCliente.setBackground(new java.awt.Color(0, 93, 139));
        botonCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonClienteMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laesmeraldasanfelipe/img/cliente.png"))); // NOI18N
        jLabel8.setText("Registro de Cliente");

        javax.swing.GroupLayout botonClienteLayout = new javax.swing.GroupLayout(botonCliente);
        botonCliente.setLayout(botonClienteLayout);
        botonClienteLayout.setHorizontalGroup(
            botonClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        botonClienteLayout.setVerticalGroup(
            botonClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(botonCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 250, -1));

        botonCaja.setBackground(new java.awt.Color(0, 93, 139));
        botonCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCajaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCajaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCajaMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laesmeraldasanfelipe/img/caja.png"))); // NOI18N
        jLabel9.setText("Caja");

        javax.swing.GroupLayout botonCajaLayout = new javax.swing.GroupLayout(botonCaja);
        botonCaja.setLayout(botonCajaLayout);
        botonCajaLayout.setHorizontalGroup(
            botonCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        botonCajaLayout.setVerticalGroup(
            botonCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(botonCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 250, -1));

        botonRespaldos1.setBackground(new java.awt.Color(0, 93, 139));
        botonRespaldos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRespaldos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRespaldos1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRespaldos1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRespaldos1MouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laesmeraldasanfelipe/img/precaucion.png"))); // NOI18N
        jLabel11.setText("Warning: Restaurar Respaldo");

        javax.swing.GroupLayout botonRespaldos1Layout = new javax.swing.GroupLayout(botonRespaldos1);
        botonRespaldos1.setLayout(botonRespaldos1Layout);
        botonRespaldos1Layout.setHorizontalGroup(
            botonRespaldos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        botonRespaldos1Layout.setVerticalGroup(
            botonRespaldos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(botonRespaldos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 250, -1));

        botonReporteVentas.setBackground(new java.awt.Color(0, 93, 139));
        botonReporteVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonReporteVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonReporteVentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonReporteVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonReporteVentasMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laesmeraldasanfelipe/img/totalventas.png"))); // NOI18N
        jLabel13.setText("Ventas Totales");

        javax.swing.GroupLayout botonReporteVentasLayout = new javax.swing.GroupLayout(botonReporteVentas);
        botonReporteVentas.setLayout(botonReporteVentasLayout);
        botonReporteVentasLayout.setHorizontalGroup(
            botonReporteVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        botonReporteVentasLayout.setVerticalGroup(
            botonReporteVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(botonReporteVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 250, -1));

        botonRespaldos.setBackground(new java.awt.Color(0, 93, 139));
        botonRespaldos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRespaldos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRespaldosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRespaldosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRespaldosMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laesmeraldasanfelipe/img/respaldo.png"))); // NOI18N
        jLabel10.setText("Respaldo");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout botonRespaldosLayout = new javax.swing.GroupLayout(botonRespaldos);
        botonRespaldos.setLayout(botonRespaldosLayout);
        botonRespaldosLayout.setHorizontalGroup(
            botonRespaldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        botonRespaldosLayout.setVerticalGroup(
            botonRespaldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(botonRespaldos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 250, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 640));

        jPanel2.setBackground(new java.awt.Color(0, 134, 190));

        jLabel12.setFont(new java.awt.Font("Roboto Light", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Hoy es:");

        jLabelfecha.setFont(new java.awt.Font("Roboto Light", 3, 24)); // NOI18N
        jLabelfecha.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jLabelfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1290, 70));

        contenedor.setBackground(new java.awt.Color(136, 212, 234));
        contenedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        contenedor.setPreferredSize(new java.awt.Dimension(981, 504));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 1040, 500));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sistema de Inventarios \"La Esmeralda\"");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 1070, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelbarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelbarraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelbarraMousePressed

    private void jPanelbarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelbarraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanelbarraMouseDragged

    private void jPanelextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelextMouseClicked
        System.exit(0);
        evt.consume();
    }//GEN-LAST:event_jPanelextMouseClicked

    private void jPanelextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelextMouseEntered
        jPanelext.setBackground(Color.red);
        jLabelX.setForeground(Color.white);
        evt.consume();
    }//GEN-LAST:event_jPanelextMouseEntered

    private void jPanelextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelextMouseExited
        jPanelext.setBackground(new Color(255,153,102));
        jLabelX.setForeground(Color.BLACK);
        evt.consume();
    }//GEN-LAST:event_jPanelextMouseExited

    private void botonRespaldosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRespaldosMouseEntered
        botonRespaldos.setBackground(new Color(0, 134, 190));
       evt.consume();
    }//GEN-LAST:event_botonRespaldosMouseEntered

    private void botonRespaldosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRespaldosMouseExited
        botonRespaldos.setBackground(new Color(0, 93, 139));
        evt.consume();
    }//GEN-LAST:event_botonRespaldosMouseExited

    private void botonRegistroInventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistroInventarioMouseEntered
        botonRegistroInventario.setBackground(new Color(0, 134, 190));
        evt.consume();
    }//GEN-LAST:event_botonRegistroInventarioMouseEntered

    private void botonRegistroInventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistroInventarioMouseExited
       botonRegistroInventario.setBackground(new Color(0, 93, 139));
       evt.consume();
    }//GEN-LAST:event_botonRegistroInventarioMouseExited

    private void botonInventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInventarioMouseEntered
        botonInventario.setBackground(new Color(0, 134, 190));
        evt.consume();
    }//GEN-LAST:event_botonInventarioMouseEntered

    private void botonInventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInventarioMouseExited
        botonInventario.setBackground(new Color(0, 93, 139));
        evt.consume();
    }//GEN-LAST:event_botonInventarioMouseExited

    private void botonProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonProductosMouseEntered
        botonProductos.setBackground(new Color(0, 134, 190));
        evt.consume();
    }//GEN-LAST:event_botonProductosMouseEntered

    private void botonProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonProductosMouseExited
        botonProductos.setBackground(new Color(0, 93, 139));
        evt.consume();
    }//GEN-LAST:event_botonProductosMouseExited

    private void botonVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVentasMouseEntered
        botonVentas.setBackground(new Color(0, 134, 190));
        evt.consume();
    }//GEN-LAST:event_botonVentasMouseEntered

    private void botonVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVentasMouseExited
        botonVentas.setBackground(new Color(0, 93, 139));
        evt.consume();
    }//GEN-LAST:event_botonVentasMouseExited

    private void botonClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonClienteMouseEntered
        botonCliente.setBackground(new Color(0, 134, 190));
        evt.consume();
    }//GEN-LAST:event_botonClienteMouseEntered

    private void botonClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonClienteMouseExited
        botonCliente.setBackground(new Color(0, 93, 139));
        evt.consume();
    }//GEN-LAST:event_botonClienteMouseExited

    private void botonCajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCajaMouseEntered
        botonCaja.setBackground(new Color(0, 134, 190));
        evt.consume();
    }//GEN-LAST:event_botonCajaMouseEntered

    private void botonCajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCajaMouseExited
        botonCaja.setBackground(new Color(0, 93, 139));
        evt.consume();
    }//GEN-LAST:event_botonCajaMouseExited

    private void botonRespaldos1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRespaldos1MouseEntered
         botonRespaldos1.setBackground(Color.red);
         evt.consume();
    }//GEN-LAST:event_botonRespaldos1MouseEntered

    private void botonRespaldos1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRespaldos1MouseExited
        botonRespaldos1.setBackground(new Color(0, 93, 139));
        evt.consume();
    }//GEN-LAST:event_botonRespaldos1MouseExited

    private void botonRegistroInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistroInventarioMouseClicked
        if (LaEsmeraldaSanfelipe.usuario.equals("admin")) {
            inventario obj = new inventario();
            contenedor.add(obj);
            obj.show();
        } else {
            JOptionPane.showMessageDialog(null, "Usuario: " + LaEsmeraldaSanfelipe.usuario + " Acceso Denegado");
        }
        evt.consume();
    }//GEN-LAST:event_botonRegistroInventarioMouseClicked

    private void botonVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVentasMouseClicked
       
        SalidaFinal obj = new SalidaFinal();
        contenedor.add(obj);
        obj.show();
        evt.consume();
        
    }//GEN-LAST:event_botonVentasMouseClicked

    private void botonClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonClienteMouseClicked
        Cliente obj = new Cliente();
        contenedor.add(obj);
        obj.show();
        evt.consume();
    }//GEN-LAST:event_botonClienteMouseClicked

    private void botonRespaldosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRespaldosMouseClicked
        javax.swing.JFileChooser jF1 = new javax.swing.JFileChooser();
        String ruta = "";

        try {

            if (jF1.showSaveDialog(null) == jF1.APPROVE_OPTION) {

                ruta = jF1.getSelectedFile().getAbsolutePath();

                //Aqui ya tiens la ruta,,,ahora puedes crear un fichero n esa ruta y escribir lo k kieras...
            }

        } catch (HeadlessException ex) {
        }
        String controlar = ruta;
        if (controlar.equals("")) {
            JOptionPane.showMessageDialog(null, "Ruta no seleccionada");

        } else {
            try {
                Process p = Runtime.getRuntime().exec("C:\\xampp\\mysql\\bin\\mysqldump -u admin -p6510 sanfelipe");

                InputStream is = p.getInputStream();

                FileOutputStream fos = new FileOutputStream(ruta + ".sql");

                byte[] buffer = new byte[1000];
                int leido = is.read(buffer);
                while (leido > 0) {
                    fos.write(buffer, 0, leido);
                    leido = is.read(buffer);
                }
                fos.close();
                JOptionPane.showMessageDialog(null, "Respaldo Exitoso");

            } catch (IOException ex) {
                Logger.getLogger(VentanaPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        evt.consume();
    }//GEN-LAST:event_botonRespaldosMouseClicked

    private void botonProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonProductosMouseClicked
        if (LaEsmeraldaSanfelipe.usuario.equals("admin")) {
            producto obj = new producto();
            contenedor.add(obj);
            obj.show();
        } else {
            JOptionPane.showMessageDialog(null, "Usuario: " + LaEsmeraldaSanfelipe.usuario + " Acceso Denegado");
        }
        evt.consume();

    }//GEN-LAST:event_botonProductosMouseClicked

    private void botonInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInventarioMouseClicked
         productoINF obj = new productoINF();
        contenedor.add(obj);
        obj.show();
        evt.consume();
    }//GEN-LAST:event_botonInventarioMouseClicked

    private void botonRespaldos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRespaldos1MouseClicked
         if (LaEsmeraldaSanfelipe.usuario.equals("admin")) {
            javax.swing.JFileChooser jF1 = new javax.swing.JFileChooser();
            String ruta = "";

            try {

                if (jF1.showSaveDialog(null) == jF1.APPROVE_OPTION) {

                    ruta = jF1.getSelectedFile().getAbsolutePath();

                    //Aqui ya tiens la ruta,,,ahora puedes crear un fichero n esa ruta y escribir lo k kieras...
                }

            } catch (HeadlessException ex) {
            }

            if (ruta.equals("")) {
                JOptionPane.showMessageDialog(null, "Archivo no Seleccionado");
            } else {
                try {
                    Process p = Runtime.getRuntime().exec("C:\\xampp\\mysql\\bin\\mysql -u admin -p6510 sanfelipe");
                    OutputStream os = p.getOutputStream();
                    FileInputStream fis = new FileInputStream(ruta);
                    byte[] buffer = new byte[1000];
                    int leido = fis.read(buffer);
                    while (leido > 0) {
                        os.write(buffer, 0, leido);
                        leido = fis.read(buffer);
                    }
                    os.flush();
                    os.close();
                    fis.close();
                    JOptionPane.showMessageDialog(null, "Restauración Exitosa");

                } catch (IOException ex) {
                    Logger.getLogger(VentanaPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Usuario: " + LaEsmeraldaSanfelipe.usuario + " No tienes permisos para hacer esa acción");
        }

    }//GEN-LAST:event_botonRespaldos1MouseClicked

    private void botonCajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCajaMouseClicked
        Caja obj = new Caja();
        contenedor.add(obj);
        obj.show();
        evt.consume();
    }//GEN-LAST:event_botonCajaMouseClicked

    private void jPanelminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelminMouseEntered
        jPanelmin.setBackground(Color.yellow);
        jLabelM.setForeground(Color.red);
        evt.consume();
    }//GEN-LAST:event_jPanelminMouseEntered

    private void jPanelminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelminMouseExited
        jPanelmin.setBackground(new Color(255,153,102));
        jLabelM.setForeground(Color.black);
        evt.consume();
    }//GEN-LAST:event_jPanelminMouseExited

    private void jPanelminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelminMouseClicked
         this.setExtendedState(ICONIFIED);
         evt.consume();
    }//GEN-LAST:event_jPanelminMouseClicked

    private void botonReporteVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReporteVentasMouseClicked
        Salida obj = new Salida();
        contenedor.add(obj);
        obj.show();
        evt.consume();
    }//GEN-LAST:event_botonReporteVentasMouseClicked

    private void botonReporteVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReporteVentasMouseEntered
        botonReporteVentas.setBackground(new Color(0, 134, 190));
        evt.consume();                    
    }//GEN-LAST:event_botonReporteVentasMouseEntered

    private void botonReporteVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReporteVentasMouseExited
        botonReporteVentas.setBackground(new Color(0, 93, 139));
        evt.consume();
    }//GEN-LAST:event_botonReporteVentasMouseExited

    public void tiempo(){
   
    LocalDate hoy = LocalDate.now();
    
    jLabelfecha.setText(hoy.toString());
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonCaja;
    private javax.swing.JPanel botonCliente;
    private javax.swing.JPanel botonInventario;
    private javax.swing.JPanel botonProductos;
    private javax.swing.JPanel botonRegistroInventario;
    private javax.swing.JPanel botonReporteVentas;
    private javax.swing.JPanel botonRespaldos;
    private javax.swing.JPanel botonRespaldos1;
    private javax.swing.JPanel botonVentas;
    private javax.swing.JDesktopPane contenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelM;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JLabel jLabelfecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelbarra;
    private javax.swing.JPanel jPanelext;
    private javax.swing.JPanel jPanelmin;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
